In [1]:
import numpy as n

In [3]:
a=n.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
b=a.reshape(2,2)
print(b)

[[1 2]
 [3 4]]


In [8]:
d=n.arange(1,9)
print(d)
c=d.reshape(2,2,2)
print(c)

[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
print(a)

[[1 2]
 [3 4]]


In [11]:
print(a.ndim)
print(d.ndim)
print(c.ndim)

2
1
3


In [12]:
print(a.shape)

(2, 2)


In [13]:
print(d.shape)

(8,)


In [14]:
print(c.shape)

(2, 2, 2)


In [15]:
print(a.dtype)

int32


In [16]:
print(d.size)

8


# 2program

In [17]:
l=[1,2,3,4,5,6,7,8,9,10]
a=n.array(l)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
b=n.random.randint(1,16,(3,5))
print(b)

[[10 12  2 10  1]
 [14 10 11 10 10]
 [ 8 12  8  4  7]]


In [24]:
a=n.empty((3,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
a=n.full((3,5),8)
print(a)

[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [27]:
a=n.zeros((3,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
a=n.ones((3,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### prg3

In [30]:
a=n.arange(14,41)
print(a)

[14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37
 38 39 40]


### prg4

In [33]:
a=n.random.randint(1,50,(8,5))
print(a)

[[45 24 17 12 41]
 [18  6 20 20 33]
 [43 13 46 23 48]
 [ 6 48 19 30  8]
 [28 40  8 33  9]
 [ 6 34 42 25 16]
 [27 16 32 19 24]
 [ 3 34 16 27 19]]


### prg5

In [35]:
b=a.reshape(4,10)
print(b)

[[45 24 17 12 41 18  6 20 20 33]
 [43 13 46 23 48  6 48 19 30  8]
 [28 40  8 33  9  6 34 42 25 16]
 [27 16 32 19 24  3 34 16 27 19]]


#### prg6

In [36]:
a[0,3]

12

In [41]:
b[0:3,4]

array([41, 48,  9])

In [43]:
print(b[2])
print(b[3])

[28 40  8 33  9  6 34 42 25 16]
[27 16 32 19 24  3 34 16 27 19]


In [45]:
print(b[:,2])
print(b[:,4])
print(b[:,5])

[17 46  8 32]
[41 48  9 24]
[18  6  6  3]


In [46]:
print(b)

[[45 24 17 12 41 18  6 20 20 33]
 [43 13 46 23 48  6 48 19 30  8]
 [28 40  8 33  9  6 34 42 25 16]
 [27 16 32 19 24  3 34 16 27 19]]


### prg7


In [56]:
print(b[b%2==1])
print(b)

[45 17 41 33 43 13 23 19 33  9 25 27 19  3 27 19]
[[45 24 17 12 41 18  6 20 20 33]
 [43 13 46 23 48  6 48 19 30  8]
 [28 40  8 33  9  6 34 42 25 16]
 [27 16 32 19 24  3 34 16 27 19]]


In [62]:
b[b%2==0]=-1
b

array([[45, -1, 17, -1, 41, -1, -1, -1, -1, 33],
       [43, 13, -1, 23, -1, -1, -1, 19, -1, -1],
       [-1, -1, -1, 33,  9, -1, -1, -1, 25, -1],
       [27, -1, -1, 19, -1,  3, -1, -1, 27, 19]])

### prg9

In [64]:
a=n.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
import numpy as n

In [6]:
a=n.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
b=n.arange(2,20,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
a3=n.append(a,b)
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  2,  4,  6,  8, 10, 12, 14,
       16, 18])

In [9]:
#reverse
a3[::-1]

array([18, 16, 14, 12, 10,  8,  6,  4,  2, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1])

In [10]:
#prg 10
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
a.resize(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
#prg11
a=n.random.randint(13,40,12)
a



array([31, 31, 29, 22, 29, 33, 37, 18, 25, 14, 34, 26])

In [20]:
a.sort()
a

array([14, 18, 22, 25, 26, 29, 29, 31, 31, 33, 34, 37])

In [22]:
a[::-1]

array([37, 34, 33, 31, 31, 29, 29, 26, 25, 22, 18, 14])

In [25]:
#prg 12
a=n.random.random((5,3))
a

array([[0.69999154, 0.42988029, 0.06544415],
       [0.70452214, 0.02559912, 0.49948765],
       [0.62169691, 0.07927748, 0.39929201],
       [0.40094754, 0.99068668, 0.51137456],
       [0.94974889, 0.86411982, 0.27279498]])

In [26]:
a+4

array([[4.69999154, 4.42988029, 4.06544415],
       [4.70452214, 4.02559912, 4.49948765],
       [4.62169691, 4.07927748, 4.39929201],
       [4.40094754, 4.99068668, 4.51137456],
       [4.94974889, 4.86411982, 4.27279498]])

In [27]:
a*2

array([[1.39998309, 0.85976059, 0.1308883 ],
       [1.40904428, 0.05119823, 0.99897531],
       [1.24339382, 0.15855496, 0.79858403],
       [0.80189507, 1.98137336, 1.02274912],
       [1.89949778, 1.72823965, 0.54558997]])

In [28]:
a-3

array([[-2.30000846, -2.57011971, -2.93455585],
       [-2.29547786, -2.97440088, -2.50051235],
       [-2.37830309, -2.92072252, -2.60070799],
       [-2.59905246, -2.00931332, -2.48862544],
       [-2.05025111, -2.13588018, -2.72720502]])

In [29]:
a/2

array([[0.34999577, 0.21494015, 0.03272208],
       [0.35226107, 0.01279956, 0.24974383],
       [0.31084846, 0.03963874, 0.19964601],
       [0.20047377, 0.49534334, 0.25568728],
       [0.47487444, 0.43205991, 0.13639749]])

In [31]:
b=n.random.randint(2,8,(3,3))
b

array([[6, 3, 2],
       [7, 2, 6],
       [3, 7, 5]])

In [32]:
print(a)
print(b)

[[0.69999154 0.42988029 0.06544415]
 [0.70452214 0.02559912 0.49948765]
 [0.62169691 0.07927748 0.39929201]
 [0.40094754 0.99068668 0.51137456]
 [0.94974889 0.86411982 0.27279498]]
[[6 3 2]
 [7 2 6]
 [3 7 5]]


In [35]:
a=n.random.randint(2,7,(3,3))
a

array([[2, 4, 2],
       [5, 4, 2],
       [4, 2, 3]])

In [36]:
a+b

array([[ 8,  7,  4],
       [12,  6,  8],
       [ 7,  9,  8]])

In [37]:
a*b

array([[12, 12,  4],
       [35,  8, 12],
       [12, 14, 15]])

In [38]:
a-b

array([[-4,  1,  0],
       [-2,  2, -4],
       [ 1, -5, -2]])

In [39]:
a/b

array([[0.33333333, 1.33333333, 1.        ],
       [0.71428571, 2.        , 0.33333333],
       [1.33333333, 0.28571429, 0.6       ]])

In [40]:
a//b

array([[0, 1, 1],
       [0, 2, 0],
       [1, 0, 0]], dtype=int32)

In [41]:
min(a+b)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [42]:
c=a+b

In [43]:
c

array([[ 8,  7,  4],
       [12,  6,  8],
       [ 7,  9,  8]])

In [44]:
c.min()

4

In [45]:
c.max()

12

In [46]:
c.sum()

69